### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by Meghadri-Koley** [SamarthTech/Samarth-Website#100]
**Add a form validation so that if the required inputs are blank then the button animation will not work**
![image](https://user-images.githubusercontent.com/77243269/208605876-e24013b1-6817-402f-8ad0-7370f27afcd9.png)

**Comment by syed-muheed** [comment]
Kindly assign this to me

**Comment by ZainabR11** [comment]
I'm confident in implementing form validation effectively. Please entrust me with this task!

**Comment by aman1205** [comment]
I want  to work on this task ,beaccuse recently work with same issue

**Comment by SamarthTech** [comment]
Assigned

**Comment by aman1205** [comment]
Give url where the problem is occur  beacause  did't find that .

**Comment by ZainabR11** [comment]
I have pulled request for improved footer section #110. Kindly consider. Zainab Rizwan-------- Original message --------From: Samarth - Tech ***@***.***>Date: Sun, 1 Oct 2023, 11:53 amTo: SamarthTech/Samarth-Website ***@***.***>Cc: ZainabR11 ***@***.***>, Assign ***@***.***>Subject: Re: [SamarthTech/Samarth-Website] Form Validation (Issue #100)
Assigned
