### ISSUE TITLE
Fix : Making contact section visible on mobile screen

### ISSUE THREAD

**Issue by yube01** [SamarthTech/Samarth-Website#113]
Content of contact section are hidden in home page 
![Screenshot (9)](https://github.com/SamarthTech/Samarth-Website/assets/114811769/a1e1c6ae-6a8f-4798-9f7d-44114ec9e26d)

It can be seen on desktop screen as well but some content are only invisible

**Comment by Basavarajakjbasuu** [comment]
If you need this issue to solve could you please assign me or else let me know Can I start to work on this

**Comment by codingniket** [comment]
Go Ahead!
